[#2dmz5v7]add card promo
anasmc97/mini_project_majoo_1 pull request #11
Opened 2022-03-14 08:46 UTC by anasmc97

2022-03-14 10:07 UTC, mnafian commented on lib/ui/widgets/card_promo.dart
> +          //height: (context.mediaHeight - 24 - CustomSize.defaultMargin),
ini memang kelupaan atau expected di comment dulu?

2022-03-14 10:10 UTC, ryanadit commented on lib/ui/widgets/card_promo.dart
> +          //height: (context.mediaHeight - 24 - CustomSize.defaultMargin),
saya comment dulu mas

2022-03-14 10:15 UTC, mnafian commented on lib/ui/widgets/card_promo.dart
> +          //height: (context.mediaHeight - 24 - CustomSize.defaultMargin),
btw ini yg punya task mas @ryanadit atau mas @anasmc97 ? kok saya liat PR dari tim yellow mas @anasmc97 semua ya? bukannya per task yg bikin PR harusnya engineer yg bersangkutan? kok ini ketuanya semua yg handle bikin PR?

2022-03-14 10:22 UTC, ryanadit commented on lib/ui/widgets/card_promo.dart
> +          //height: (context.mediaHeight - 24 - CustomSize.defaultMargin),
ini yg punya task saya sih mas, cuma mas @anasmc97 yg buat PR nya

2022-03-14 10:31 UTC, mnafian commented on lib/ui/widgets/card_promo.dart
> +          //height: (context.mediaHeight - 24 - CustomSize.defaultMargin),
tanggung jawab tim lead cuma buat skeleton projectnya aja, yg bikin PR tetep engineer bersangkutan, sepertinya ada misskom, harusnya kalo ada hal yg belum jelas di konfirmasi dan ditanyakan dulu cc @anasmc97 @ryanadit @rfaturriza , ini masih ada task yg belum dibuat PRnya atau sudah semua tinggal review ya?

2022-03-14 10:37 UTC, rfaturriza commented on lib/ui/widgets/card_promo.dart
> +          //height: (context.mediaHeight - 24 - CustomSize.defaultMargin),
> btw ini yg punya task mas @ryanadit atau mas @anasmc97 ? kok saya liat PR dari tim yellow mas @anasmc97 semua ya? bukannya per task yg bikin PR harusnya engineer yg bersangkutan? kok ini ketuanya semua yg handle bikin PR?

ohh, baik mas. saya nangkapnya kemarin yang handle PR dari lead. terimakasih mas, jadi masukan buat kami.

2022-03-14 10:40 UTC, rfaturriza requested changes

2022-03-14 10:40 UTC, rfaturriza commented on lib/ui/widgets/card_promo.dart
> +        //focalRadius: 1.5,
code yang di komen kayaknya dihapus saja

2022-03-14 10:46 UTC, rfaturriza commented on lib/ui/widgets/card_promo.dart
> +        //focalRadius: 1.5,
code yang di komen kayaknya dihapus saja

2022-03-14 10:51 UTC, ryanadit commented on lib/ui/widgets/card_promo.dart
> +        //focalRadius: 1.5,
ok siap mas

2022-03-14 11:19 UTC, ryanadit approved these changes

2022-03-15 04:53 UTC, rfaturriza approved these changes

2022-03-15 06:38 UTC, mnafian approved these changes

2022-03-15 06:51 UTC, merged