[#2dmz5v7]Task/add slider
anasmc97/mini_project_majoo_1 pull request #13
Opened 2022-03-14 09:19 UTC by anasmc97

changes:

-add slider

2022-03-14 09:49 UTC, mnafian requested changes

2022-03-14 09:49 UTC, mnafian commented on lib/ui/widgets/slider.dart
> +      heightContainer = widget.heightContent!;
better `widget?.heightContent ?? 0` aja, atau kalo gak jangan bikin nullable, waktu passing param heightnya aja pengecekannya.

2022-03-14 09:49 UTC, mnafian commented on lib/ui/widgets/slider.dart
> +    ))
trailing comma, dirapihin lagi formattingnya

2022-03-14 09:49 UTC, mnafian commented on lib/ui/widgets/slider.dart
> +    final decorationCard = BoxDecoration(
ini kepanjangan di wrap di satu method build widget, di pecah lagi jadi decoration funtion sendiri aja biar tinggal nerima param

2022-03-14 09:49 UTC, mnafian commented on lib/ui/widgets/slider.dart
> +        ));
idem, formattingnya kasih trailing comma

2022-03-14 09:49 UTC, mnafian commented on lib/ui/widgets/slider.dart
> +    Widget backButton = SafeArea(
di extract jadi widget sendiri aja diluar build method

2022-03-14 09:49 UTC, mnafian commented on lib/ui/widgets/slider.dart
> +                          onPageChanged: (index, reason) =>  setState(() => _onChange(index))),
trailing comma

2022-03-14 09:49 UTC, mnafian commented on lib/ui/widgets/slider.dart
> +                ]),
idem, trailing comma, cek2 yg lain juga ya dibawah

2022-03-14 09:49 UTC, mnafian commented on lib/ui/widgets/slider.dart
> +
ini kenapa ada space sepanjang ini? formatnya dirapihin lagi

2022-03-14 09:49 UTC, mnafian commented on lib/ui/widgets/slider_widget_image.dart
> +class SliderWidgetImage extends StatefulWidget {
ini perbedaan usage sama class slider sebelumnya apa ya?

2022-03-14 09:49 UTC, mnafian commented on lib/ui/widgets/slider_widget_image.dart
> +      heightContainer = widget.heightContent!;
idem sama komentar diatas, hindari penggunaan `!` pada null object, better pake `?` buat nullable handling

2022-03-14 09:49 UTC, mnafian commented on lib/ui/widgets/slider_widget_image.dart
> +    final decorationCard = BoxDecoration(
idem sama komentar sebelumnya masalah extract jadi function sendiri

2022-03-14 10:45 UTC, ryanadit commented on lib/ui/widgets/slider_widget_image.dart
> +class SliderWidgetImage extends StatefulWidget {
nah tadi seharusnya task ini task yg buat ulang mas, tapi berbeda branch, terus kita buat branch baru untuk buat task ulangnya mas

2022-03-14 10:58 UTC, ryanadit commented on lib/ui/widgets/slider.dart
> +      heightContainer = widget.heightContent!;
sudah saya revisi mas

2022-03-14 10:58 UTC, ryanadit commented on lib/ui/widgets/slider.dart
> +    ))
sudah direvisi mas

2022-03-14 10:58 UTC, ryanadit commented on lib/ui/widgets/slider.dart
> +    final decorationCard = BoxDecoration(
noted, sudah direvisi mas

2022-03-14 10:59 UTC, ryanadit commented on lib/ui/widgets/slider.dart
> +        ));
sudah direvisi mas

2022-03-14 10:59 UTC, ryanadit commented on lib/ui/widgets/slider.dart
> +    Widget backButton = SafeArea(
noted, sudah direvisi mas

2022-03-14 11:09 UTC, ryanadit approved these changes

2022-03-15 05:04 UTC, rfaturriza approved these changes

2022-03-15 06:31 UTC, mnafian approved these changes

2022-03-15 06:50 UTC, merged