[#2duje6t] task/Search and navbar
anasmc97/mini_project_majoo_1 pull request #7
Opened 2022-03-14 07:26 UTC by anasmc97

change: 
- add navbar
-  add search bar
-  update model

2022-03-14 07:49 UTC, ryanadit reviewed
Home page mungkin di push nya kalau semua komponen sudah direview

2022-03-14 07:51 UTC, rfaturriza reviewed
- untuk file homepage sepertinya tidak perlu dipush agar tidak tertimpa di main
- navbar widget menggunakan stateless sesuai dengan sop development

2022-03-14 07:55 UTC, anasmc97 commented
> Home page mungkin di push nya kalau semua komponen sudah direview



> Home page mungkin di push nya kalau semua komponen sudah direview

baik mas

2022-03-14 07:55 UTC, mnafian commented
> * untuk file homepage sepertinya tidak perlu dipush agar tidak tertimpa di main
> * navbar widget menggunakan stateless sesuai dengan sop development

selama memang widget itu membutuhkan state changes operation **masih diperbolehkan** untuk saat ini karena kita belom implement bloc mas @rfaturriza

2022-03-14 07:58 UTC, rfaturriza commented
> > * untuk file homepage sepertinya tidak perlu dipush agar tidak tertimpa di main
> > * navbar widget menggunakan stateless sesuai dengan sop development
> 
> selama memang widget itu membutuhkan state changes operation **masih diperbolehkan** untuk saat ini karena kita belom implement bloc mas @rfaturriza

ok mas

2022-03-14 08:00 UTC, mnafian requested changes

2022-03-14 08:00 UTC, mnafian commented on lib/ui/pages/home_page.dart
> +                        color: CustomColors.selectedIconColor),
kasih trailing comma biar rapi formattingnya, cek juga yg bawah2 jika terlalu panjang dalam 1 lines

2022-03-14 08:00 UTC, mnafian commented on lib/ui/pages/home_page.dart
> +                        color: CustomColors.selectedIconColor),
idem

2022-03-14 08:00 UTC, mnafian commented on lib/ui/pages/home_page.dart
> +                        color: CustomColors.selectedIconColor),
idem

2022-03-14 08:00 UTC, mnafian commented on lib/ui/pages/home_page.dart
> +                label: "Profile")
idem, kasih trailing comma

2022-03-14 08:00 UTC, mnafian commented on lib/ui/pages/home_page.dart
> +                fontWeight: FontWeight.w400, color: CustomColors.fontSecondary),
idem

2022-03-14 08:00 UTC, mnafian commented on lib/ui/widgets/navbar.dart
> +                const Color(0xFF6E8DDD).withOpacity(0.6),
ini colorsnya emang expected gak di taruh di constant tersendiri?

2022-03-14 08:00 UTC, mnafian commented on lib/ui/widgets/search_text_field.dart
> +                borderSide: const BorderSide(color: Colors.white)),
ini dirapiin lagi trailing comma

2022-03-14 08:00 UTC, mnafian commented on lib/ui/widgets/search_text_field.dart
> +                borderSide: const BorderSide(color: Colors.white))),
idem

2022-03-14 08:01 UTC, ryanadit commented
> > * untuk file homepage sepertinya tidak perlu dipush agar tidak tertimpa di main
> > * navbar widget menggunakan stateless sesuai dengan sop development
> 
> selama memang widget itu membutuhkan state changes operation **masih diperbolehkan** untuk saat ini karena kita belom implement bloc mas @rfaturriza

siap mas

2022-03-14 08:10 UTC, rfaturriza commented on lib/models/product.dart
> +}
pakai named parameter saja agar lebih mudah di passing

2022-03-14 08:23 UTC, anasmc97 commented on lib/ui/widgets/navbar.dart
> +                const Color(0xFF6E8DDD).withOpacity(0.6),
Sbnenrya sudah ada mas, cman lupa sy gunakan mas

2022-03-14 08:23 UTC, anasmc97 commented on lib/ui/widgets/search_text_field.dart
> +                borderSide: const BorderSide(color: Colors.white)),
sudah mas

2022-03-14 08:23 UTC, anasmc97 commented on lib/ui/widgets/search_text_field.dart
> +                borderSide: const BorderSide(color: Colors.white))),
sudah mas

2022-03-14 08:24 UTC, anasmc97 commented on lib/models/product.dart
> +}
sudah mas

2022-03-14 08:53 UTC, anasmc97 commented on lib/ui/pages/home_page.dart
> +                        color: CustomColors.selectedIconColor),
file homepage sudah sy hapus, agar tidak ketimpa dengan file skeletonnya

2022-03-14 08:53 UTC, anasmc97 commented on lib/ui/pages/home_page.dart
> +                        color: CustomColors.selectedIconColor),
file homepage sudah sy hapus, agar tidak ketimpa dengan file skeletonnya mas

2022-03-14 08:53 UTC, anasmc97 commented on lib/ui/pages/home_page.dart
> +                        color: CustomColors.selectedIconColor),
file homepage sudah sy hapus, agar tidak ketimpa dengan file skeletonnya mas

2022-03-14 08:53 UTC, anasmc97 commented on lib/ui/pages/home_page.dart
> +                label: "Profile")
file homepage sudah sy hapus, agar tidak ketimpa dengan file skeletonnya mas

2022-03-14 08:53 UTC, anasmc97 commented on lib/ui/pages/home_page.dart
> +                fontWeight: FontWeight.w400, color: CustomColors.fontSecondary),
_file homepage sudah sy hapus, agar tidak ketimpa dengan file skeletonnya mas_

2022-03-15 06:35 UTC, ryanadit approved these changes

2022-03-15 06:37 UTC, mnafian approved these changes

2022-03-15 07:22 UTC, merged