Task/description button counter
anasmc97/mini_project_majoo_1 pull request #9
Opened 2022-03-14 08:37 UTC by anasmc97

2022-03-14 10:17 UTC, mnafian requested changes

2022-03-14 10:17 UTC, mnafian commented on lib/ui/widgets/detail_body_product.dart
> +      required this.productPrice})
trailing comma

2022-03-14 10:17 UTC, mnafian commented on lib/ui/widgets/detail_body_product.dart
> +      width: MediaQuery.of(context).orientation == Orientation.portrait
ini MediaQuery better dijadikan extension seperti yg aku contohkan kemaren aja biar manggilnya lebih simple

2022-03-14 10:31 UTC, rfaturriza approved these changes
lanjut

2022-03-14 10:32 UTC, mnafian commented
ini tasknya @rfaturriza ternyata ya? mangkanya kirain @anasmc97 semua yg kerjain, diskusinya ada di PR sebelah.

2022-03-14 13:49 UTC, ryanadit reviewed
mungkin bisa di manfaatkan mas context extensionnya

2022-03-14 13:53 UTC, ryanadit commented on lib/ui/widgets/detail_body_product.dart
> +          : MediaQuery.of(context).size.width * 0.5,
ini bisa manfaatkan context extentionnya mas, ada size widthnya juga

2022-03-14 14:09 UTC, rfaturriza commented on lib/ui/widgets/detail_body_product.dart
> +          : MediaQuery.of(context).size.width * 0.5,
oke siap, lupa update yang ini.

2022-03-15 05:37 UTC, ryanadit approved these changes

2022-03-15 06:18 UTC, mnafian approved these changes

2022-03-15 07:33 UTC, merged